### ISSUE TITLE
Error: Cannot find module '@prisma/photon' For Prisma 2 Typescript examples

### ISSUE THREAD

**Issue by Albert-Gao** [prisma/prisma-examples#1024]
Just `git clone` the latest `prisma-examples`

Go to `typescript/graphql-auth` or `graphql-apollo-server`,

run `npm i`

## Round 1

error:

```bash
AlbertGao@Albert-LottoNZ-Laptop graphql-auth % npm i

> prisma2@2.0.0-preview016.2 install /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/prisma2
> node download-build/index.js || echo ""

> Downloading darwin binary for query-engine and migration-engine [====================] 100%


> core-js@2.6.10 postinstall /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/core-js
> node postinstall || echo "ignore"


> @prisma/sdk@0.0.60 postinstall /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/@prisma/sdk
> node scripts/download.js

> Downloading darwin binary for query-engine [====================] 100%


> graphql-shield@5.7.3 postinstall /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/graphql-shield
> lightercollective postinstall


                                        
                .,:;;:,.                
           .,:;rrssssssrr;:,.           
      .,:;rssssssssssssssssssr;:,.      
     ;rssssssssssssrrssssssssssssr;     
    .ssssssssssssr:  :rssssssssssss.    
    .rssssssr::;;:,::,:;;::rssssssr.    
     ;ssssss:  ;r:;ss;:r:  ;ssssss;     
     ,sssssss:;r:;ssss;:r::sssssss:     
      ;ssssss:,:rssssssr:,:ssssss;      
      .rssss:  ,;;;;;;;;,  ;ssssr.      
       .rsssr;;;::;::;;;;;;rsssr.       
        .;sssssssr:  :ssssssss;.        
          :rsssssssrrsssssssr:          
           .:rssssssssssssr:.           
             .:;rssssssr;,.             
                .,;;;;,.                


     *** Thank you for using graphql-shield! ***

  Please consider donating to our open collective
       to help us maintain this package.

  https://opencollective.com/graphql-shield/donate

                    ***


> graphql-auth@ postinstall /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth
> npm -s run generate

> Downloading darwin binary for query-engine [====================] 100%

Generating Photon.js to /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/@generated/photon
Done in 2.42s

Error: Failed to import photon package at @prisma/photon. The following error occured while trying:

        Error: Cannot find module '@prisma/photon'
Require stack:
- /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/dist/dmmf/utils.js
- /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/dist/dmmf/index.js
- /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/dist/builder.js
- /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/dist/index.js
- /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/src/schema.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.exports.get (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/dmmf/utils.ts:12:27)
    at new SchemaBuilder (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/builder.ts:164:38)
    at Object.build (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/builder.ts:91:19)
    at Object.onInstall (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/index.ts:43:16)
    at /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus/src/builder.ts:700:44
    at Array.forEach (<anonymous>)
    at Object.exports.get (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/dmmf/utils.ts:14:11)
    at new SchemaBuilder (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/builder.ts:164:38)
    at Object.build (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/builder.ts:91:19)
    at Object.onInstall (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus-prisma/src/index.ts:43:16)
    at /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus/src/builder.ts:700:44
    at Array.forEach (<anonymous>)
    at SchemaBuilder.beforeWalkTypes (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus/src/builder.ts:694:18)
    at SchemaBuilder.getFinalTypeMap (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus/src/builder.ts:784:10)
    at makeSchemaInternal (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus/src/builder.ts:1571:15)
    at Object.makeSchema (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/nexus/src/builder.ts:1616:49)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-auth@ postinstall: `npm -s run generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-auth@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AlbertGao/.npm/_logs/2019-11-24T11_10_55_995Z-debug.log
AlbertGao@Albert-LottoNZ-Laptop graphql-auth % 
```

In https://github.com/prisma/photonjs/issues/56 , it mentioned
 https://github.com/prisma/photonjs/pull/143 should fix it, I saw that merge, and there is no output in this `schema.prisma`, but still not working.

I already global installed `prisma2`. but still not working.

I am using Node v13.2.0, tried `12.13.0` without any luck.

Tried adding `@prisma/photon` and `prisma2` to devDependencies, still not work. Error is different though.

=======================================

## Round 2

After `git reset --hard` and `rm -rf ./node_modules`

I updated the prisma2 version in this project to `2.0.0-alpha.351`: it asks me to install an `@prisma/photon` now! Exciting! But still error. :(

and I am using `NPM` but the command seems to use `yarn`?

```bash
> graphql-auth@ postinstall /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth
> npm -s run generate

In order to use the "photonjs" generator, you need to install @prisma/photon to your project.
✔ Do you want to install it now? … yes
yarn add v1.19.0
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning graphql-yoga > @types/graphql@14.5.0: This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.
warning graphql-yoga > apollo-upload-server@7.1.0: Please migrate to https://npm.im/graphql-upload (see https://git.io/fADhl).
warning graphql-yoga > apollo-server-lambda > apollo-server-core > graphql-extensions > core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Couldn't find any versions for "@prisma/photon" that matches "b8d90fea39d266b128b4d748db5aca8505bb1026"
? Please choose a version of "@prisma/photon" from this list: 2.0.0-alpha.351
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > graphql-shield@5.7.3" has unmet peer dependency "graphql-middleware@^2.0.0 || ^3.0.0".
warning "graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-lambda > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.19.1", while you're on "1.19.0".
info To upgrade, run the following command:
$ brew upgrade yarn
success Saved 120 new dependencies.
info Direct dependencies
├─ @prisma/photon@2.0.0-alpha.351
├─ bcryptjs@2.4.3
├─ graphql-shield@5.7.3
├─ graphql-yoga@1.18.3
├─ graphql@14.5.8
├─ jsonwebtoken@8.5.1
├─ nexus-prisma@0.6.1
├─ nexus@0.12.0-rc.5
└─ prisma2@2.0.0-alpha.351
info All dependencies
├─ @babel/runtime@7.7.4
├─ @prisma/photon@2.0.0-alpha.351
├─ @types/aws-lambda@8.10.13
├─ @types/body-parser@1.17.1
├─ @types/connect@3.4.32
├─ @types/cors@2.8.6
├─ @types/express@4.17.2
├─ @types/graphql-deduplicator@2.0.0
├─ @types/graphql@14.5.0
├─ @types/mime@2.0.1
├─ @types/range-parser@1.2.3
├─ @types/serve-static@1.13.3
├─ @types/yup@0.26.18
├─ @types/zen-observable@0.5.4
├─ @wry/equality@0.1.9
├─ accepts@1.3.7
├─ apollo-cache-control@0.1.1
├─ apollo-link@1.2.13
├─ apollo-server-core@1.4.0
├─ apollo-server-express@1.4.0
├─ apollo-server-lambda@1.3.6
├─ apollo-server-module-graphiql@1.4.0
├─ apollo-tracing@0.1.4
├─ apollo-upload-server@7.1.0
├─ apollo-utilities@1.3.2
├─ array-flatten@1.1.1
├─ async-limiter@1.0.1
├─ backo2@1.0.2
├─ bcryptjs@2.4.3
├─ body-parser-graphql@1.1.0
├─ body-parser@1.19.0
├─ buffer-equal-constant-time@1.0.1
├─ busboy@0.2.14
├─ camelcase@5.3.1
├─ content-disposition@0.5.3
├─ cookie-signature@1.0.6
├─ cookie@0.4.0
├─ core-js@2.6.10
├─ cors@2.8.5
├─ deprecated-decorator@0.1.6
├─ destroy@1.0.4
├─ dicer@0.2.5
├─ ecdsa-sig-formatter@1.0.11
├─ ee-first@1.1.1
├─ eventemitter3@3.1.2
├─ express@4.17.1
├─ fast-json-stable-stringify@2.0.0
├─ finalhandler@1.1.2
├─ fn-name@2.0.1
├─ forwarded@0.1.2
├─ fs-capacitor@1.0.1
├─ fs-extra@8.1.0
├─ graphql-deduplicator@2.0.5
├─ graphql-import@0.7.1
├─ graphql-middleware@4.0.1
├─ graphql-playground-middleware-express@1.7.11
├─ graphql-playground-middleware-lambda@1.7.12
├─ graphql-shield@5.7.3
├─ graphql-subscriptions@0.5.8
├─ graphql-tools@4.0.6
├─ graphql-upload@8.1.0
├─ graphql-yoga@1.18.3
├─ graphql@14.5.8
├─ http-errors@1.7.3
├─ inherits@2.0.4
├─ ipaddr.js@1.9.0
├─ isarray@0.0.1
├─ jsonfile@4.0.0
├─ jsonwebtoken@8.5.1
├─ jwa@1.4.1
├─ jws@3.2.2
├─ lightercollective@0.3.0
├─ lodash.includes@4.3.0
├─ lodash.isboolean@3.0.3
├─ lodash.isinteger@4.0.4
├─ lodash.isnumber@3.0.3
├─ lodash.isplainobject@4.0.6
├─ lodash.isstring@4.0.1
├─ lodash.once@4.1.1
├─ lodash@4.17.15
├─ media-typer@0.3.0
├─ merge-descriptors@1.0.1
├─ methods@1.1.2
├─ mime-db@1.42.0
├─ mime-types@2.1.25
├─ mime@1.6.0
├─ negotiator@0.6.2
├─ nexus-prisma@0.6.1
├─ nexus@0.12.0-rc.5
├─ object-assign@4.1.1
├─ object-hash@1.3.1
├─ path-to-regexp@0.1.7
├─ pluralize@8.0.0
├─ prisma2@2.0.0-alpha.351
├─ property-expr@1.5.1
├─ proxy-addr@2.0.5
├─ raw-body@2.4.0
├─ regenerator-runtime@0.13.3
├─ resolve-from@4.0.0
├─ safe-buffer@5.1.2
├─ safer-buffer@2.1.2
├─ semver@5.7.1
├─ serve-static@1.14.1
├─ source-map-support@0.5.16
├─ source-map@0.6.1
├─ string_decoder@0.10.31
├─ subscriptions-transport-ws@0.9.16
├─ symbol-observable@1.2.0
├─ synchronous-promise@2.0.10
├─ toposort@2.0.2
├─ type-is@1.6.18
├─ universalify@0.1.2
├─ unpipe@1.0.0
├─ utils-merge@1.0.1
├─ uuid@3.3.3
├─ vary@1.1.2
├─ ws@5.2.2
├─ yup@0.27.0
├─ zen-observable-ts@0.8.20
└─ zen-observable@0.8.15
$ npm -s run generate
Error: Error: Command failed with ENOENT: /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/prisma2/query-engine-darwin cli --dmmf
spawn /Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/prisma2/query-engine-darwin ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: 
    Error: Command failed with exit code 1: yarn add @prisma/photon@b8d90fea39d266b128b4d748db5aca8505bb1026
        at makeError (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/prisma2/build/index.js:359510:11)
        at handlePromise (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/prisma2/build/index.js:359755:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-auth@ postinstall: `npm -s run generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-auth@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AlbertGao/.npm/_logs/2019-11-24T11_19_52_586Z-debug.log
AlbertGao@Albert-LottoNZ-Laptop graphql-auth % git diff
diff --git a/typescript/graphql-auth/package.json b/typescript/graphql-auth/package.json
index 317d1cba..fc5b37ab 100644
--- a/typescript/graphql-auth/package.json
+++ b/typescript/graphql-auth/package.json
@@ -13,6 +13,7 @@
     "seed": "ts-node prisma/seed"
   },
   "dependencies": {
+    "@prisma/photon": "^2.0.0-alpha.351",
     "bcryptjs": "2.4.3",
     "graphql": "14.5.8",
     "graphql-shield": "5.7.3",
@@ -27,7 +28,7 @@
     "@types/jsonwebtoken": "8.3.5",
     "@types/node": "12.12.12",
     "@types/ws": "6.0.3",
-    "prisma2": "2.0.0-preview016.2",
:...skipping...
diff --git a/typescript/graphql-auth/package.json b/typescript/graphql-auth/package.json
index 317d1cba..fc5b37ab 100644
--- a/typescript/graphql-auth/package.json
+++ b/typescript/graphql-auth/package.json
@@ -13,6 +13,7 @@
     "seed": "ts-node prisma/seed"
   },
   "dependencies": {
+    "@prisma/photon": "^2.0.0-alpha.351",
     "bcryptjs": "2.4.3",
     "graphql": "14.5.8",
     "graphql-shield": "5.7.3",
@@ -27,7 +28,7 @@
     "@types/jsonwebtoken": "8.3.5",
     "@types/node": "12.12.12",
     "@types/ws": "6.0.3",
-    "prisma2": "2.0.0-preview016.2",
+    "prisma2": "2.0.0-alpha.351",
     "ts-node": "8.5.2",
     "ts-node-dev": "1.0.0-pre.44",
     "typescript": "3.7.2"
~
~
~
~
~
AlbertGao@Albert-LottoNZ-Laptop graphql-auth % 
```
====================================

## Round 3

After `git reset --hard` and `rm -rf ./node_modules`

This time I use `yarn install` with `2.0.0-alpha.351`

Error :( ......

```bash
AlbertGao@Albert-LottoNZ-Laptop graphql-auth % yarn install
yarn install v1.19.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > graphql-shield@5.7.3" has unmet peer dependency "graphql-middleware@^2.0.0 || ^3.0.0".
warning "graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning " > nexus-prisma@0.6.1" has unmet peer dependency "@prisma/photon@^2.0.0-alpha.351".
[4/4] 🔨  Building fresh packages...
$ npm -s run generate
In order to use the "photonjs" generator, you need to install @prisma/photon to your project.
✔ Do you want to install it now? … yes

yarn add v1.19.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@prisma/photon" that matches "b8d90fea39d266b128b4d748db5aca8505bb1026"
? Please choose a version of "@prisma/photon" from this list: 2.0.0-alpha.351
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > graphql-shield@5.7.3" has unmet peer dependency "graphql-middleware@^2.0.0 || ^3.0.0".
warning "graphql-yoga > graphql-playground-middleware-lambda@1.7.12" has unmet peer dependency "aws-lambda@^0.1.2".
warning "graphql-yoga > graphql-subscriptions@0.5.8" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core@1.4.0" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.1.1" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.4" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
warning "graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.10" has incorrect peer dependency "graphql@0.10.x - 0.13.x".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @prisma/photon@2.0.0-alpha.351
info All dependencies
└─ @prisma/photon@2.0.0-alpha.351
$ npm -s run generate
> Downloading darwin binary for query-engine [====================] 100%

Generating Photon.js to ./node_modules/@prisma/photon
Done in 2.58s

sh: ts-node: command not found
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: 
    Error: Command failed with exit code 1: yarn add @prisma/photon@b8d90fea39d266b128b4d748db5aca8505bb1026
        at makeError (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/prisma2/build/index.js:359510:11)
        at handlePromise (/Users/AlbertGao/codes/temp/prisma-examples/typescript/graphql-auth/node_modules/prisma2/build/index.js:359755:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
AlbertGao@Albert-LottoNZ-Laptop graphql-auth % 
```

Interesting, because ts-node is in the devDep, or is it the command it tried to run?

=====================

## Round 4

After adding `@prisma/photon` to dep list, seems it is working?

```bash
......
..... 
> graphql-auth@ postinstall /Users/AlbertGao/codes/temp/prisma2-ts-graphql-auth
> npm -s run generate
> Downloading darwin binary for query-engine [====================] 100%

Generating Photon.js to ./node_modules/@prisma/photon
Done in 2.64s

You should specify a configuration value for outputs in Nexus' makeSchema. Provide one to remove this warning.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN graphql-shield@5.7.3 requires a peer of graphql-middleware@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-playground-middleware-lambda@1.7.12 requires a peer of aws-lambda@^0.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@0.5.8 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-server-core@1.4.0 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-cache-control@0.1.1 requires a peer of graphql@0.10.x - 0.13.x but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.1.4 requires a peer of graphql@0.10.x - 0.13.x but none is installed. You must install peer dependencies yourself.
npm WARN graphql-extensions@0.0.10 requires a peer of graphql@0.10.x - 0.13.x but none is installed. You must install peer dependencies yourself.
npm WARN graphql-auth@ No repository field.

added 385 packages from 350 contributors and audited 787 packages in 23.387s

2 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
AlbertGao@Albert-LottoNZ-Laptop prisma2-ts-graphql-auth % 
```

This warning `You should specify a configuration value for outputs in Nexus' makeSchema. Provide one to remove this warning.`

needs to fix or just ignore?

Anyway, the `npm run start` and `npm run build` have errors:

```bash
AlbertGao@Albert-LottoNZ-Laptop prisma2-ts-graphql-auth % npm run start

> graphql-auth@ start /Users/AlbertGao/codes/temp/prisma2-ts-graphql-auth
> node dist/server

internal/modules/cjs/loader.js:957
    throw err;
    ^

Error: Cannot find module '/Users/AlbertGao/codes/temp/prisma2-ts-graphql-auth/dist/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-auth@ start: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-auth@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AlbertGao/.npm/_logs/2019-11-24T12_01_11_331Z-debug.log
AlbertGao@Albert-LottoNZ-Laptop prisma2-ts-graphql-auth % npm run build

> graphql-auth@ build /Users/AlbertGao/codes/temp/prisma2-ts-graphql-auth
> npm -s run clean && npm -s run generate && tsc

> Downloading darwin binary for query-engine [====================] 100%

Generating Photon.js to ./node_modules/@prisma/photon
Done in 2.70s

You should specify a configuration value for outputs in Nexus' makeSchema. Provide one to remove this warning.
src/context.ts:1:24 - error TS2307: Cannot find module '@generated/photon'.

1 import { Photon } from '@generated/photon'
                         ~~~~~~~~~~~~~~~~~~~

src/types/Post.ts:6:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

6     t.model.id()
        ~~~~~

src/types/Post.ts:9:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

9     t.model.published()
        ~~~~~

src/types/Post.ts:10:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

10     t.model.title()
         ~~~~~

src/types/Post.ts:11:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

11     t.model.content()
         ~~~~~

src/types/Post.ts:12:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"Post">'.

12     t.model.author()
         ~~~~~

src/types/User.ts:6:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

6     t.model.id()
        ~~~~~

src/types/User.ts:7:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

7     t.model.name()
        ~~~~~

src/types/User.ts:8:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

8     t.model.email()
        ~~~~~

src/types/User.ts:9:7 - error TS2339: Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.

9     t.model.posts({ pagination: false })
        ~~~~~


Found 10 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! graphql-auth@ build: `npm -s run clean && npm -s run generate && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the graphql-auth@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AlbertGao/.npm/_logs/2019-11-24T12_01_28_316Z-debug.log
AlbertGao@Albert-LottoNZ-Laptop prisma2-ts-graphql-auth % 
```

====================
I think Round 4 is close? If that is the case, can we use `npm` or have to use `yarn`?

I think the easy way to solve it is to update the dep list in `package.json`? To include the `@prisma/photon`?

What am I missing? Thanks :)

**Comment by timsuchanek** [comment]
Thanks @Albert-Gao! Which branch of the examples are you on?

**Comment by Albert-Gao** [comment]
`prisma2` branch: 

I use this command from the doc: `git clone --single-branch --branch prisma2 git@github.com:prisma/prisma-examples.git`

I don't know if I get it working or not:

1. I added `@prisma/photon` to the dep, and align its version with `prisma2` in the devDep
1. The generate command will give a warning like: `GraphQL Nexus: Unable to find file or module @generated/photon, skipping`
1. Change all the `@generated/photon` in project to `@prisma/photon`
1. lift
1. prisma2 generate
1. restart IDE

Seems all working!

Don't know if I get it right or not, just one thing that do not understand,if I want to update the model schema or GraphQL schema, how to do? I tried to:
1. change the `schema.ts`
1. then `prisma2 lift save --name add nickname`

but the `life` does not work, it said Everything is up to date.

By the way, very impressed with the work, the whole schema definition abstracts the database, and can access the ORM in one place, very very straightforward. And everything just clicks without much learning if you have the basics concepts of ORM and GraphQL!

Thanks, keep the hard work! Love it, if I did anything wrong, let me know!

**Comment by nikolasburk** [comment]
Hey @Albert-Gao, it seems this was a versioning issue where there version of `nexus-prisma` in the example was already updated to work with the [latest version](https://github.com/prisma/prisma2/releases/tag/2.0.0-preview017) of Photon.js (which we only released today).

With the new version out, everything should work as expected. I'm closing this issue, but definitely feel free to reopen it if you still encounter the same issue! 🙂
