### ISSUE TITLE
typescript/graphql-sdl-first: post.author is not working

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-examples#1484]
Related to https://github.com/prisma/prisma-client-js/issues/513

For the following GraphQL query:

```GraphQL
query {
  feed {
    id
    content
    author {
      id
      name
      email
    }
  }
}
```

I'm getting this error:

```
  engine stdout { timestamp: 'Feb 21 14:24:17.391',
  level: 'ERROR',
  target: 'prisma',
  fields:
   { message: 'PANIC',
     reason: 'called `Option::unwrap()` on a `None` value',
     file:
      '/rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs',
     line: 15,
     column: 40 } } +21ms
  engine { error:
  engine    { Error: socket hang up
  engine        at createHangUpError (_http_client.js:323:15)
  engine        at Socket.socketOnEnd (_http_client.js:426:23)
  engine        at Socket.emit (events.js:203:15)
  engine        at endReadableNT (_stream_readable.js:1145:12)
  engine        at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } } +1ms
  prisma-client Error: PANIC
  prisma-client     at currentRequestPromise.then.catch.e (/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/node_modules/@prisma/client/runtime/index.js:1:16175)
  prisma-client     at process._tickCallback (internal/process/next_tick.js:68:7) +8ms
Error: 
Invalid `prisma.posts.findOne()` invocation in
/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/src/schema.ts:71:18

   67 return ctx.prisma.post.findMany({
   68   where: {
   69     OR: [
   70       { title: { contains: args.searchString } },
→  71       PANIC
    at PrismaClientFetcher.request (/Users/prisma/prisma/prisma-examples/typescript/graphql-sdl-first/node_modules/@prisma/client/index.js:89:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

reproduction available at https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-sdl-first:

```
git clone https://github.com/prisma/prisma-examples
cd prisma-examples/typescript/graphql-sdl-first
yarn install
prisma2 generate
yarn dev &
pid=$!

sleep 10

curl 'http://localhost:4000/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"query {\n  feed {\n    id\n    content\n    author {\n      id\n      name\n      email\n    }\n  }\n}"}' --compressed

kill "$pid"
```

**Comment by nikolasburk** [comment]
This was the same issue as: https://github.com/prisma/prisma-examples/issues/1389 Now fixed ✅
