### ISSUE TITLE
graphql-apollo-server JS example error : can't npm run dev 

### ISSUE THREAD

**Issue by willy20040711** [prisma/prisma-examples#1524]
I follow the guideline and complete the step of "npx prisma2 introspect" &  "npx prisma2 generate".

I reproduce this error in both two situations. 
1. add the profile schema in "graphql-apollo-server JS example".
2. when I try to connect to our own mysql database.

DB: mysql
node version: 12.0.0
prisma2:2.0.0-preview022

Then, I got below error..
```
/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/dmmf/DmmfDocument.ts:130
      throw new Error(
            ^
Error: Could not find field 'Query.undefined' on type Query
    at OutputType.getField (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/dmmf/DmmfDocument.ts:130:13)
    at utils_1.flatMap.map.mappedField (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/mapping.ts:56:41)
    at Array.map (<anonymous>)
    at Object.exports.getCrudMappedFields (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/mapping.ts:52:64)
    at renderNexusPrismaInputs (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/typegen.ts:117:25)
    at render (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/typegen.ts:46:3)
    at doGenerate (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/typegen.ts:27:25)
    at Object.generateSync (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/typegen.ts:13:3)
    at new SchemaBuilder (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/builder.ts:240:15)
    at Object.build (/Users/labfnp/project/0224/3/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/src/builder.ts:138:19)

```
My schema.js:
```
const { nexusPrismaPlugin } = require('nexus-prisma')
const { idArg, makeSchema, objectType, stringArg } = require('nexus')

const Users = objectType({
  name: 'Users',
  definition(t) {
    t.model.id()
    t.model.username()
    t.model.email()
  },
})

const Recipes = objectType({
  name: 'Recipes',
  definition(t) {
    t.model.id()
    t.model.perfumeName()
  },
})


const Query = objectType({
  name: 'Query',
  definition(t) {
    t.crud.Recipes()
    t.list.field('feed', {
      type: 'Recipes',
      resolve: (_, args, ctx) => {
        return ctx.prisma.Recipes.findOne({
          where: { id: 500 },
        })
      },
    })
  },
})



const schema = makeSchema({
  types: [ Users, Query, Recipes],
  plugins: [nexusPrismaPlugin()],
  outputs: {
    schema: __dirname + '/generated/schema.graphql',
    typegen: __dirname + '/generated/nexus.ts',
  },
  typegenAutoConfig: {
    contextType: 'Context.Context',
    sources: [
      {
        source: '@prisma/client',
        alias: 'prisma',
      },
      {
        source: require.resolve('./context'),
        alias: 'Context',
      },
    ],
  },
})

module.exports = {
  schema
}
```

**Comment by createvo** [comment]
Hello, 
have you tried `t.crud.recipes()` instead of `t.crud.Recipes()`

Anyway, for a model is a good practice to use singular names **Recipe**, and NOT plural names **Recipes**

**Comment by nikolasburk** [comment]
Hey @willy20040711, sorry for the delay on this one! Since the issue rather seems to be related to working with Prisma and Nexus itself rather than a concrete problem with an example, I suggest to open up another issue in the respective repos if the problem still persists for you 🙂
