### ISSUE TITLE
[javascript/graphql-apollo-server] Error of npm run dev

### ISSUE THREAD

**Issue by xiote** [prisma/prisma-examples#2058]
```
➜  xiote git clone https://github.com/prisma/prisma-examples.git --depth=1
Cloning into 'prisma-examples'...
remote: Enumerating objects: 660, done.
remote: Counting objects: 100% (660/660), done.
remote: Compressing objects: 100% (398/398), done.
remote: Total 660 (delta 232), reused 413 (delta 159), pack-reused 0
Receiving objects: 100% (660/660), 182.62 KiB | 367.00 KiB/s, done.
Resolving deltas: 100% (232/232), done.
```

```
➜  xiote cd prisma-examples/javascript/graphql-apollo-server
➜  graphql-apollo-server git:(latest) npm install
npm WARN deprecated nexus-prisma@0.12.0: The nexus-prisma package has merged into nexus-plugin-prisma. Learn more here: https://nxs.li/nexus-prisma-to-nexus-plugin-prisma/about.

> @prisma/cli@2.8.0 preinstall /Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/@prisma/cli
> node preinstall/index.js


> @prisma/cli@2.8.0 install /Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/@prisma/cli
> node download-build/index.js


> core-js@3.6.5 postinstall /Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> @apollo/protobufjs@1.0.5 postinstall /Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/@apollo/protobufjs
> node scripts/postinstall


> @prisma/client@2.8.0 postinstall /Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/@prisma/client
> node scripts/postinstall.js

Prisma Schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (version: 2.8.0) to ./node_modules/@prisma/client in 45ms

You can now start using Prisma Client in your code:


import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()


Explore the full API: http://pris.ly/d/client
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @nexus/schema@0.15.0 requires a peer of graphql@^14.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN nexus-prisma@0.12.0 requires a peer of @nexus/schema@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN nexus-prisma@0.12.0 requires a peer of @prisma/client@2.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
npm WARN nexus-prisma@0.12.0 requires a peer of graphql@^14.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@1.1.0 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-upload@8.1.0 requires a peer of graphql@0.13.1 - 14 but none is installed. You must install peer dependencies yourself.
npm WARN typescript-javascript@ No repository field.
npm WARN typescript-javascript@ No license field.

added 199 packages from 225 contributors and audited 200 packages in 5.473s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
➜  graphql-apollo-server git:(latest) npm run dev

> typescript-javascript@ dev /Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server
> node ./src/server.js

/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/dmmf/transformer.js:35
    let inputType = arg.inputType.some(a => a.kind === 'enum')
                                  ^

TypeError: Cannot read property 'some' of undefined
    at transformArg (/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/dmmf/transformer.js:35:35)
    at Array.map (<anonymous>)
    at transformInputType (/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/dmmf/transformer.js:101:14)
    at /Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/dmmf/transformer.js:24:48
    at Array.map (<anonymous>)
    at transformSchema (/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/dmmf/transformer.js:24:39)
    at transform (/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/dmmf/transformer.js:11:17)
    at Object.exports.getTransformedDmmf (/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/dmmf/transformer.js:5:100)
    at new SchemaBuilder (/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/builder.js:109:24)
    at Object.build (/Users/xiote/github.com/xiote/prisma-examples/javascript/graphql-apollo-server/node_modules/nexus-prisma/dist/builder.js:50:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-javascript@ dev: `node ./src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-javascript@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiote/.npm/_logs/2020-10-05T04_58_43_963Z-debug.log
```

**Comment by xiote** [comment]
"@prisma/client": "2.7.1" is ok
but  "@prisma/client": "2.8.0" is error

**Comment by divyenduz** [comment]
@xiote Thanks for reporting this, we are aware of this issue and this will be fixed via https://github.com/prisma/prisma-examples/issues/2094

**Comment by zayabattogtokh** [comment]
"@prisma/client": "2.7.1" is ok
Also:
- yarn add --dev prisma@latest
- yarn add @prisma/client@latest
