### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::4000

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#2171]
````
+++++++++++
executing .github/tests/./typescript/subscriptions-pubsub/run.sh (tests)
yarn run v1.22.5
$ npm run generate:prisma
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1603911179469-0.4817221266893308/node but npm is using /opt/hostedtoolcache/node/12.19.0/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> subscriptions-pubsub@ generate:prisma /home/runner/work/prisma-examples/prisma-examples/typescript/subscriptions-pubsub
> prisma generate

Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (version: 2.10.0) to ./node_modules/@prisma/client in 65ms

You can now start using Prisma Client in your code:

```
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
```

Explore the full API: http://pris.ly/d/client
$ cross-env NODE_ENV=development tsnd --no-notify --respawn --transpileOnly ./src
Using ts-node version 8.10.2, typescript version 4.0.5
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1317:16)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at /home/runner/work/prisma-examples/prisma-examples/typescript/subscriptions-pubsub/node_modules/apollo-server/src/index.ts:127:18
    at new Promise (<anonymous>)
    at ApolloServer.<anonymous> (/home/runner/work/prisma-examples/prisma-examples/typescript/subscriptions-pubsub/node_modules/apollo-server/src/index.ts:122:11)
    at Generator.next (<anonymous>)
    at /home/runner/work/prisma-examples/prisma-examples/typescript/subscriptions-pubsub/node_modules/apollo-server/dist/index.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/prisma-examples/prisma-examples/typescript/subscriptions-pubsub/node_modules/apollo-server/dist/index.js:14:12)

**Comment by janpio** [comment]
Easiest thing to unblock will probably be to just use a different port in the project (and the ones following later) until things work again - and open a PR again with a revert commit to keep a reproduction that we then can investigate and fix later.
