### ISSUE TITLE
node-graphql-schema-delegation example error 'Cannot read property 'query' of undefined'

### ISSUE THREAD

**Issue by alaarihan** [prisma/prisma-examples#22]
I tried to run masters query from node-graphql-schema-delegation example playground but I got this error:
```
Server is running on localhost:4000
TypeError: Cannot read property 'query' of undefined
    at masters (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/src/resolvers/Query.js:2:56)
    at resolveFieldValueOrError (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/graphql/execution/execute.js:531:18)
    at resolveField (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/graphql/execution/execute.js:495:16)
    at /home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/graphql/execution/execute.js:361:42)
    at executeOperation (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/graphql/execution/execute.js:289:122)
    at executeImpl (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/graphql/execution/execute.js:154:14)
    at Object.execute (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/graphql/execution/execute.js:131:229)
    at doRunQuery (/home/ubuntu/workspace/prisma-examples/node-graphql-schema-delegation/node_modules/apollo-server-core/dist/runQuery.js:124:42)
```

**Comment by kennetpostigo** [comment]
I'm also running into this in my project, aside from this, doing delegation of mutations is really tedious because in the `schema.graphql` I have to copy and paste over the `input` types from the `prisma-schema.js` file. Is there a better method for delegating mutations?

**Comment by abhiaiyer91** [comment]
So we removed `$delegate` from the Prisma Client. I'm going to be updating these examples to use the Prisma Binding. For now, I suggest using the binding for cases you want to delegate.

If you're using the `db` in your context for the client, add a `binding` property for the prisma binding!

**Comment by abhiaiyer91** [comment]
Both the node delegation and typescript delegation examples have been updated to use prisma binding. Thanks for reporting this @alaarihan !

**Comment by alaarihan** [comment]
Thank you @abhiaiyer91
