### ISSUE TITLE
Expect to add vercel/pkg build example

### ISSUE THREAD

**Issue by SturdyCat** [prisma/prisma-examples#2300]

**Comment by nikolasburk** [comment]
Hey @SturdyCat, thanks a lot for opening this issue! Can you provide a bit more information what this issue is about exactly? Right now it's not really possible to infer that just from your title.

**Comment by SturdyCat** [comment]
```  json
# prisma-examples/javascript/graphql-apollo-server/
# package.json
...
 "scripts": {
    "build:pkg": "pkg . --out-path ./dist --debug"
  },
...
  "pkg": {
    "scripts": [
      "src/**/*.js"
    ],
    "assets": [
      "prisma/**/*",
      "src/**/*",
      "schema.graphql",
      "package.json",
      "node_modules/.prisma/**/*"
    ],
    "targets": [
      "node14-macos-x64"
    ]
  }
```

```shell
# pkg build node
yarn build:pkg
# cd dist, run exec
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot write to packaged file
    at writeToSnapshot (pkg/prelude/bootstrap.js:575:16)
    at Object.fs.writeSync (pkg/prelude/bootstrap.js:583:12)
    at Object.writeFileSync (fs.js:1393:26)
    at writeFileSync (/snapshot/graphql-apollo-server/node_modules/fs-jetpack/lib/write.js:46:8)
    at Object.writeSync [as sync] (/snapshot/graphql-apollo-server/node_modules/fs-jetpack/lib/write.js:75:3)
    at Object.write (/snapshot/graphql-apollo-server/node_modules/fs-jetpack/lib/jetpack.js:241:13)
    at Object.hardWriteFileSync (/snapshot/graphql-apollo-server/node_modules/nexus-plugin-prisma/dist/utils.js:72:8)
    at doGenerate (/snapshot/graphql-apollo-server/node_modules/nexus-plugin-prisma/dist/typegen/render.js:50:17)
    at Object.generateSync (/snapshot/graphql-apollo-server/node_modules/nexus-plugin-prisma/dist/typegen/render.js:30:5)
    at new SchemaBuilder (/snapshot/graphql-apollo-server/node_modules/nexus-plugin-prisma/dist/builder.js:136:21)
```

**Comment by nikolasburk** [comment]
Thanks a lot for sharing this! It seems that you're trying to use `pkg` with the `javascript/graphql-apollo-server/` example, is that correct?

I think this would be an interesting deployment use case, but as specified [here](https://github.com/prisma/prisma-examples/blob/latest/CONTRIBUTING.md#example-guidelines) the purpose of the examples is to provide _minimal_ and functional rather than production-ready examples or being ready to be deployed with a variety of deployment tools.
