### ISSUE TITLE
example grpc run `npm run dev` get error

### ISSUE THREAD

**Issue by huang12zheng** [prisma/prisma-examples#2479]
* error log:
> /Users/huangzheng/.npm/_logs/2021-02-04T04_56_48_003Z-debug.log

```log
0 verbose cli [
0 verbose cli   '/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/node',
0 verbose cli   '/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/npm',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/huangzheng/.nvm/versions/node/v15.5.0/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/huangzheng/frontend/prisma-examples/typescript/grpc/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/huangzheng/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/Users/huangzheng/.nvm/versions/node/v15.5.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 verbose npm-session b573e62d3857de35
20 timing npm:load Completed in 11ms
21 timing command:run-script Completed in 1685ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/Users/huangzheng/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose cwd /Users/huangzheng/frontend/prisma-examples/typescript/grpc
24 verbose Darwin 19.6.0
25 verbose argv "/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/node" "/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/npm" "run" "dev"
26 verbose node v15.5.0
27 verbose npm  v7.3.0
28 error code 1
29 error path /Users/huangzheng/frontend/prisma-examples/typescript/grpc
30 error command failed
31 error command sh -c ts-node ./server/server.ts
32 verbose exit 1

```

* terminal:
```log
(base) ➜  grpc git:(latest) ✗ npm run dev    

> dev
> ts-node ./server/server.ts


/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
server/server.ts:4:10 - error TS2305: Module '"../node_modules/@prisma/client"' has no exported member 'PrismaClient'.

4 import { PrismaClient } from '@prisma/client'
           ~~~~~~~~~~~~

    at createTSError (/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR! code 1
npm ERR! path /Users/huangzheng/frontend/prisma-examples/typescript/grpc
npm ERR! command failed
npm ERR! command sh -c ts-node ./server/server.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huangzheng/.npm/_logs/2021-02-04T05_30_33_267Z-debug.log
```

# fix it:
~run `sudo prisma generate`~
add `"postinstall": "prisma generate"` to package.json

> It has to do with #2478

**Comment by huang12zheng** [comment]
close with no reply
