### ISSUE TITLE
example grpc run `npm run dev` get error

### ISSUE THREAD

**Issue by huang12zheng** [prisma/prisma-examples#2480]
> It has to do with #2478
> It has to do with #2479

* terminal log
```log
(base) ➜  grpc git:(latest) ✗ npm run dev         

> dev
> ts-node ./server/server.ts

Error: Failed to load /Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown/grpc_node.node. Cannot find module '/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/grpc/src/node/extension_binary/node-v88-darwin-x64-unknown/grpc_node.node'
Require stack:
- /Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/grpc/src/grpc_extension.js
- /Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/grpc/src/client_interceptors.js
- /Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/grpc/src/client.js
- /Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/grpc/index.js
- /Users/huangzheng/frontend/prisma-examples/typescript/grpc/server/server.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/huangzheng/frontend/prisma-examples/typescript/grpc/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
npm ERR! code 1
npm ERR! path /Users/huangzheng/frontend/prisma-examples/typescript/grpc
npm ERR! command failed
npm ERR! command sh -c ts-node ./server/server.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huangzheng/.npm/_logs/2021-02-04T05_37_33_798Z-debug.log
```

/Users/huangzheng/.npm/_logs/2021-02-04T05_37_33_798Z-debug.log
```log
0 verbose cli [
0 verbose cli   '/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/node',
0 verbose cli   '/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/npm',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/Users/huangzheng/.nvm/versions/node/v15.5.0/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/huangzheng/frontend/prisma-examples/typescript/grpc/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/huangzheng/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/Users/huangzheng/.nvm/versions/node/v15.5.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session b5ea3c6cd4e3e635
20 timing npm:load Completed in 12ms
21 timing command:run-script Completed in 1655ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/Users/huangzheng/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose cwd /Users/huangzheng/frontend/prisma-examples/typescript/grpc
24 verbose Darwin 19.6.0
25 verbose argv "/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/node" "/Users/huangzheng/.nvm/versions/node/v15.5.0/bin/npm" "run" "dev"
26 verbose node v15.5.0
27 verbose npm  v7.3.0
28 error code 1
29 error path /Users/huangzheng/frontend/prisma-examples/typescript/grpc
30 error command failed
31 error command sh -c ts-node ./server/server.ts
32 verbose exit 1

```

**Comment by huang12zheng** [comment]
https://zhuanlan.zhihu.com/p/163705754
2021 GRPC no longer maintained

**Comment by huang12zheng** [comment]
```ts
import chalk from 'chalk'
const PROTO_PATH = __dirname + '/../service.proto'

import { PrismaClient } from '@prisma/client'
import * as protoLoader from '@grpc/proto-loader'
import * as grpc from '@grpc/grpc-js'

const prisma = new PrismaClient()

const packageDefinition = protoLoader.loadSync(PROTO_PATH, {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true,
})
const { blog } = grpc.loadPackageDefinition(packageDefinition) as any

async function post(call: any, callback: any) {
  const { id } = call.request
  const post = await prisma.post.findUnique({
    where: {
      id,
    },
  })
  callback(null, post)
}

async function feed(call: any, callback: any) {
  const feed = await prisma.post.findMany({
    where: { published: true },
  })
  callback(null, { feed })
}

async function filterPosts(call: any, callback: any) {
  const { searchString } = call.request
  const filteredPosts = await prisma.post.findMany({
    where: {
      OR: [
        {
          title: {
            contains: searchString,
          },
        },
        {
          content: {
            contains: searchString,
          },
        },
      ],
    },
  })
  callback(null, { filteredPosts })
}

async function signupUser(call: any, callback: any) {
  const { email, name } = call.request
  try {
    const newUser = await prisma.user.create({
      data: {
        name,
        email,
      },
    })
    callback(null, newUser)
  } catch (e) {
    callback(e, null)
  }
}

async function createDraft(call: any, callback: any) {
  const { title, content, authorEmail } = call.request
  try {
    const newDraft = await prisma.post.create({
      data: {
        title,
        content,
        published: false,
        author: { connect: { email: authorEmail } },
      },
    })
    callback(null, newDraft)
  } catch (e) {
    callback(e, null)
  }
}

async function deletePost(call: any, callback: any) {
  const { id } = call.request
  try {
    const deletedPost = await prisma.post.delete({
      where: {
        id,
      },
    })
    callback(null, deletedPost)
  } catch (e) {
    callback(e, null)
  }
}

async function publish(call: any, callback: any) {
  const { id } = call.request
  try {
    const publishedPost = await prisma.post.update({
      where: { id },
      data: { published: true },
    })
    callback(null, publishedPost)
  } catch (e) {
    callback(e, null)
  }
}

const server = new grpc.Server()
server.addService(blog.Blog.service, {
  feed,
  post,
  filterPosts,
  signupUser,
  createDraft,
  publish,
  deletePost,
})
server.bindAsync('0.0.0.0:50051', grpc.ServerCredentials.createInsecure(),
  () => main()
)

function main() {
  const message = `
The gRPC server is being started on ${chalk.bold(
    `0.0.0.0:50051`
  )}. You now can invoke any client script by its name, e.g.:

${chalk.bold(`$ npm run feed`)}
or
${chalk.bold(`$ npm run signupUser`)}

See ${chalk.bold(
    `package.json`
  )} for a list of all available scripts or use ${chalk.bold(
    `BloomRPC`
  )} if you prefer a GUI client (download: ${chalk.bold(
    `https://github.com/uw-labs/bloomrpc`
  )}).
`
  console.log(message)
  server.start()
}


```

```json
{
  "name": "typescript-grpc",
  "dependencies": {
    "@grpc/grpc-js": "^1.1.0",
    "@grpc/proto-loader": "0.5.6",
    "@prisma/client": "2.16.0",
    "chalk": "4.1.0"
  },
  "scripts": {
    "dev": "ts-node ./server/server.ts",
    "seed": "ts-node prisma/seed.ts",
    "feed": "ts-node ./client/feed.ts",
    "filterPosts": "ts-node ./client/filterPosts.ts",
    "post": "ts-node ./client/post.ts",
    "signupUser": "ts-node ./client/signupUser.ts",
    "createDraft": "ts-node ./client/createDraft.ts",
    "publish": "ts-node ./client/publish.ts",
    "deletePost": "ts-node ./client/deletePost.ts"
  },
  "devDependencies": {
    "prisma": "2.16.0",
    "@types/node": "13.13.40",
    "ts-node": "9.1.1",
    "typescript": "4.1.3"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}

```

**Comment by huang12zheng** [comment]
> https://zhuanlan.zhihu.com/p/163705754
> 2021 GRPC no longer maintained

https://github.com/grpc/grpc-node/issues/1673

Can I make a PR to migrate?
@nikolasburk or someone to reply me.

**Comment by huang12zheng** [comment]
close with no reply
