### ISSUE TITLE
Seed script not working in the Next.js REST API example

### ISSUE THREAD

**Issue by robertsiipola** [prisma/prisma-examples#2668]
Hi,

After I've downloaded the [example](https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes) and ran the prisma migrate script I try to run the following script, given in the readme:
`npx prisma db seed --preview-feature`. This leads to the following error:

```
We detected a seed file at `prisma/seed.ts` but it seems that you do not have the following dependencies installed:
- ts-node

To install them run: yarn add -D ts-node

Running ts-node "prisma/seed.ts" ...
/bin/sh: ts-node: command not found
Error: Command failed with exit code 127: ts-node "prisma/seed.ts"
```

So I installed ts-node with `yarn add -D ts-node`. Running the seed script now with ts-node installed, prompts the following error:
```
import { PrismaClient } from '@prisma/client';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module.m._compile (/Users/robertsiipola/rest-nextjs-api-routes/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/robertsiipola/rest-nextjs-api-routes/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main (/Users/robertsiipola/rest-nextjs-api-routes/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/Users/robertsiipola/rest-nextjs-api-routes/node_modules/ts-node/src/bin.ts:288:3)
Error: Command failed with exit code 1: ts-node "prisma/seed.ts"
```

I also tried playing around with the `require` keyword but to no success. Any thoughts?

**Comment by robertsiipola** [comment]
Alright so after reading your documentation a little bit, I managed to fix this by adding the following compiler options for the ts-node script: `"ts-node": "ts-node --compiler-options '{\"module\":\"CommonJS\"}'"`. You can find it [here](https://www.prisma.io/docs/guides/application-lifecycle/seed-database), under step four, adding compiler options.
