### ISSUE TITLE
Seed command fails

### ISSUE THREAD

**Issue by hnrw** [prisma/prisma-examples#3153]
Running `npx prisma db seed`  in the `rest-nextjs-api-routes` gives the following error.

```
An error occured while running the seed command:
/home/henry/projects/prisma/rest-nextjs-api-routes/prisma/seed.ts:37
import { PrismaClient } from '@prisma/client';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1117:16)
    at Module._compile (internal/modules/cjs/loader.js:1165:27)
    at Module.m._compile (/home/henry/projects/prisma/rest-nextjs-api-routes/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .ts] (/home/henry/projects/prisma/rest-nextjs-api-routes/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at main (/home/henry/projects/prisma/rest-nextjs-api-routes/node_modules/ts-node/src/bin.ts:331:12)
    at Object.<anonymous> (/home/henry/projects/prisma/rest-nextjs-api-routes/node_modules/ts-node/src/bin.ts:482:3)
```

I followed the steps given in the readme: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes

Interestingly, seeding the database works fine in the typescript rest-express project. 

I'm not too experienced with TS, so maybe there's something obvious I'm missing. But it would be better if the example worked out of the box.

**Comment by Ningensei848** [comment]
In my case, I solved the problem by running the `seed` command with the compiler option. (Rewrite your `package.json` like below)

cf. https://github.com/prisma/prisma-examples/issues/2668#issuecomment-803274884

```package.json
.
.
    "prisma": "3.0.2",
    "typescript": "4.4.3"
  },
  "prisma": {
    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
  }
```

---

in terminal:

```terminal
$ npx prisma db seed
Environment variables loaded from .env
Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
Start seeding ...
Created user with id: 1
Created user with id: 2
Created user with id: 3
Seeding finished.

🌱  The seed command has been executed.
```
---

**Comment by DonikaV** [comment]
@Ningensei848 
```

An error occured while running the seed command:
Error: ENOENT: no such file or directory, open '/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/.prisma/client/schema.prisma'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at new LibraryEngine (/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/@prisma/client/runtime/index.js:24876:42)
    at PrismaClient.getEngine (/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/@prisma/client/runtime/index.js:37537:16)
    at new PrismaClient (/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/@prisma/client/runtime/index.js:37506:29)
    at Object.<anonymous> (/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/prisma/seed.ts:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/ts-node/src/index.ts:1313:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/.prisma/client/schema.prisma',
  clientVersion: '3.1.1'
}

```

**Comment by janpio** [comment]
> Error: ENOENT: no such file or directory, open '/Users/valeriidonika/Code/nc-board/rest-nextjs-api-routes-auth/node_modules/.prisma/client/schema.prisma'

Is this correct? Should it exist (or did you set a custom `output` folder in your  `generator` block`)?
