### ISSUE TITLE
ERROR: getUserByAccount is not a function

### ISSUE THREAD

**Issue by JoeAshworth** [prisma/prisma-examples#3381]
Following the fullstack example [here](https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nextjs-api-routes-auth).

Following the instructions to the letter, everything was going fine until I tried to login with NextAuth and Github until I received this error:

```event - compiled successfully in 86 ms (409 modules)
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error getUserByAccount is not a function {
  message: 'getUserByAccount is not a function',
  stack: 'TypeError: getUserByAccount is not a function\n' +
    '    at Object.callback (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next-auth/core/routes/callback.js:81:39)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async NextAuthHandler (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next-auth/core/index.js:133:28)\n' +
    '    at async NextAuthNextHandler (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next-auth/next/index.js:20:19)\n' +
    '    at async Object.apiResolver (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next/dist/server/api-utils.js:102:9)\n' +
    '    at async DevServer.handleApiRequest (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next/dist/server/next-server.js:1054:9)\n' +
    '    at async Object.fn (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next/dist/server/next-server.js:941:37)\n' +
    '    at async Router.execute (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next/dist/server/router.js:222:32)\n' +
    '    at async DevServer.run (/Users/joeashworth/Personal/rest-nextjs-api-routes-auth/node_modules/next/dist/server/next-server.js:1125:29)',
  name: 'TypeError'
}
  ```

  
  Thought you might like to know! :)

**Comment by goranefbl** [comment]
Finally resolved the problem. On my side issue was that I tried to update packages, but since it moved to monorepo, I had to uninstall it first, then install it again.

Run:

`npm uninstall next-auth @next-auth/prisma-adapter`

then:

`npm install @next-auth/prisma-adapter`

This fixed it for me.

**Comment by ruheni** [comment]
Hi @JoeAshworth 👋🏽

I've updated the example. Let me know if you're still running into the error – if you do, you can go ahead and re-open the issue. 🙂

**Comment by gkhulbe4** [comment]
i am still getting this error.

**Comment by GloireMutaliko21** [comment]
The error occures with a custom adapter ! Any solution ??
