### ISSUE TITLE
Next.js GraphQL example giving error on step "npx prisma db seed"

### ISSUE THREAD

**Issue by ameetmadan** [prisma/prisma-examples#3450]
Error:
```
~/PATH/prisma-graphql-nextjs/ npx prisma db seed
Running seed command `ts-node prisma/seed.ts` ...
Start seeding ...
PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
/PATH/prisma-graphql-nextjs/prisma/seed.ts:55:38

   52 try {
   53   console.log(`Start seeding ...`)
   54   for (const u of userData) {
→  55     const user = await prisma.user.create(
  Unique constraint failed on the fields: (`email`)
    at cb (/PATH/prisma-graphql-nextjs/node_modules/@prisma/client/runtime/index.js:38688:17)
    at async main (/PATH/prisma-graphql-nextjs/prisma/seed.ts:55:20) {
  code: 'P2002',
  clientVersion: '3.7.0',
  meta: { target: [ 'email' ] }
}

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts
```

**Comment by nikolasburk** [comment]
Thanks for opening this issue @ameetmadan, seems like this is an issue in most examples at the moment because `npx prisma migrate dev` actually already calls `npx prisma db seed` under the hood. The error then occurs because the `email` field is marked as `@unique` in the Prisma schema, so creating `User` records with the same `email` again violates the unique-constraint.

We'll fix this soon 🙏

**Comment by ruheni** [comment]
Hey @ameetmadan 👋🏽

Thanks for raising this. #3499 should resolve this issue. Don't hesitate to reach out if you run into any further issues :)
