### ISSUE TITLE
typescript/graphql example: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#420]
When following the instructions in the README of the [typescript/graphql](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql) example, I'm getting the following error after running `npm run start`:

```
$ npm run start

> typescript-graphql@ start /Users/nikolasburk/Desktop/prisma-examples/typescript/graphql
> ts-node-dev --no-notify --respawn --transpileOnly ./src

Using ts-node version 8.0.2, typescript version 3.3.1
TypeError: Cannot read property 'length' of undefined
    at Object.suggestionList (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/utils.js:43:32)
    at PrismaSchemaBuilder.SchemaBuilder.missingType (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:180:35)
    at PrismaSchemaBuilder.SchemaBuilder.getOrBuildType (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:432:21)
    at PrismaSchemaBuilder.SchemaBuilder.getInputType (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:397:25)
    at /Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:299:51
    at Array.forEach (<anonymous>)
    at PrismaSchemaBuilder.SchemaBuilder.buildArgs (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:296:27)
    at PrismaSchemaBuilder.SchemaBuilder.buildObjectField (/Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:285:24)
    at /Users/nikolasburk/Desktop/prisma-examples/typescript/graphql/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:258:57
    at Array.forEach (<anonymous>)
[ERROR] 10:53:17 TypeError: Cannot read property 'length' of undefined
```

**Comment by otrebu** [comment]
I changed the way the start script to:

`nodemon -e ts -x ts-node src/server.ts`

and I got some better error than the above:

`TSError: ⨯ Unable to compile TypeScript:
src/index.ts(21,21): error TS2345: Argument of type '"Post"' is not assignable to parameter of type 'BaseScalars'.
src/index.ts(30,28): error TS2345: Argument of type '"Post"' is not assignable to parameter of type 'BaseScalars'.
src/index.ts(47,21): error TS2345: Argument of type '"Post"' is not assignable to parameter of type 'BaseScalars'.
src/index.ts(59,27): error TS2345: Argument of type '"User"' is not assignable to parameter of type 'BaseScalars'.
src/index.ts(72,28): error TS2345: Argument of type '"Post"' is not assignable to parameter of type 'BaseScalars'.
src/index.ts(89,27): error TS2345: Argument of type '"Post"' is not assignable to parameter of type 'BaseScalars'.
src/index.ts(99,24): error TS2345: Argument of type '"Post"' is not assignable to parameter of type 'BaseScalars'.`

**Comment by funthomas** [comment]
maybe is problem in version of Nexus 
in repo nexus-prisma is used version 0.7.0-alpha.2 in prisma example repo is used nexus 0.9.7

**Comment by funthomas** [comment]
when i use nexus 0.7.0-alpha.2

problem with args is gone, but still have some issues

 Error: Missing type AuthPayload, did you forget to import a type or mean BatchPayload?
    at PrismaSchemaBuilder.SchemaBuilder.missingType (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:185:15)
    at PrismaSchemaBuilder.SchemaBuilder.getOrBuildType (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:432:21)
    at PrismaSchemaBuilder.SchemaBuilder.getOutputType (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:404:25)
    at PrismaSchemaBuilder.SchemaBuilder.buildObjectField (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:282:48)
    at /Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:258:57
    at Array.forEach (<anonymous>)
    at PrismaSchemaBuilder.SchemaBuilder.buildObjectFields (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:252:27)
    at fields (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/nexus-prisma/node_modules/nexus/dist/builder.js:151:68)
    at resolveThunk (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/graphql/type/definition.js:374:40)
    at defineFieldMap (/Users/tombo/Projects/Prisma/examples/typescript/graphql-auth/node_modules/graphql/type/definition.js:528:18)
[ERROR] 15:03:06 Error: Missing type AuthPayload, did you forget to import a type or mean BatchPayload?

**Comment by kevinmarrec** [comment]
@otrebu I think `nodemon` + `ts-node` is really slow to restart comparing to `ts-node-dev`, and we shouldn't have errors in editor. So I guess it's only something wrong around `nexus-prisma` or `nexus` last version(s).

For the error, Got this error at a point of time, somehow you need to keep the `generated/nexus.ts` the first time you run the server. But it could be cool if @nikolasburk could tell us how to make it work without it. Cause I think the project should work if we remove the `generated` folder (and it could also be relevant to not have it in the GitHub repo at all, as it's generated stuff).

**Comment by kevinmarrec** [comment]
@funthomas Yeah it's surely a change since 0.7.0-alpha2 that causes the issue, but I prefer stick with last version (that is not alpha btw) and try to find out what made the thing break :D

**Comment by kevinmarrec** [comment]
After investigating a bit more, it seems that `idArg`, `stringArg`, etc ... from `nexus` are mismatching with what `args` wants to receive.
```js
args: {
  someString: stringArg() // Error
}
```
but as something like
```js
args: {
  someString: { type: 'String' }
}
```

For example, this code works : 
```js
const Mutation = prismaObjectType('Mutation', t => {
  t.field('createPost', 'Post', {
    args: {
      title: { type: 'String' },
      authorEmail: { type: 'String' }
    },
    resolve: (parent, { title, authorEmail }, ctx) => {
      return ctx.prisma.createPost({
        title: title,
        author: {
          connect: {
            email: authorEmail
          }
        }
      })
    },
  })
})
```

BUT, well, you need to define the arguments, **SAVE** so that your server restart and generate typedefs for these arguments to be THEN available in the `resolver`.

If you have the `Argument of type '"Post"' is not assignable to parameter of type 'BaseScalars'`, it's because in fact you need to do `const Post = prismaObjectType('Post')` and give it to `makePrismaSchema`, then **SAVE** to have the type definition generated and accessible in `fields`.

**Comment by otrebu** [comment]
> @otrebu I think `nodemon` + `ts-node` is really slow to restart comparing to `ts-node-dev`, and we shouldn't have errors in editor. So I guess it's only something wrong around `nexus-prisma` or `nexus` last version(s).
> 
> For the error, Got this error at a point of time, somehow you need to keep the `generated/nexus.ts` the first time you run the server. But it could be cool if @nikolasburk could tell us how to make it work without it. Cause I think the project should work if we remove the `generated` folder (and it could also be relevant to not have it in the GitHub repo at all, as it's generated stuff).

Thanks @kevinmarrec, I am a bit new to the TS world, but basically I just wanted to highlight the better errors I got from using `nodemon` + `ts-node`. I found `ts-node-dev` error not very clear. 
Regardless of this, the problem is surely in some changes in `nexus-prisma` or `nexus`.

Thanks you for investigating, I will give it a try later!

**Comment by nikolasburk** [comment]
There were quite some issues with `nexus` and `nexus-prisma` over the last few days, but now everything should be stable again. I just updated the graphql and graphql-auth examples to account for all the changes that were introduced 👍

**Comment by kevinmarrec** [comment]
@nikolasburk Yeah, I updated to last versions/behaviors after reading the last Prisma Blog post, and everything rocks now 👌.

**Comment by lterfloth** [comment]
Little offtopic but just a quick question regarding nexus-prisma. What is the equivalent to `t.list.string("tags")` to fill a field of type [String!]! in the resolvers of nexus-prisma? The property list does not exist on type t and the examples don't help atm. I thought maybe someone would be able to help me here. Are there any better ways of contacting the community, beside the forum?
