### ISSUE TITLE
Cannot find module 'prisma-client-lib'

### ISSUE THREAD

**Issue by brianyang** [prisma/prisma-examples#686]
unable to start boilerplate app 

steps to reproduce issue: 

1. graphql new-app 
2. select typescript-advanced
3. cd into new-app
4. yarn start 

observe following error: 

```
yarn start
yarn run v1.17.3
warning package.json: No license field
$ dotenv -- nodemon -e ts,graphql -x ts-node src/index.ts
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `ts-node src/index.ts`

/Users/app/new-app/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/generated/prisma-client/index.ts(10,8): error TS2307: Cannot find module 'prisma-client-lib'.

    at createTSError (/Users/brian/Public/app/new-app/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/brian/Public/app/new-app/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/brian/Public/app/new-app/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/brian/Public/app/new-app/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/brian/Public/app/new-app/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by brianyang** [comment]
issue resolved with:

`yarn add prisma-client-lib`

where can i add this in the code so that other users won't have the same issue?
