### ISSUE TITLE
Error: Not Authorised!

### ISSUE THREAD

**Issue by gHashTag** [prisma/prisma-examples#805]
Played all the steps in this example
https://github.com/prisma/prisma-examples/tree/master/node/graphql-auth
but upon request

```
mutation {
  writeComment(
    postId: "ck0s5cssnii0f0b175f5umhjx" 
    text: "I like turtles 🐢"
  ) {
    id
    text
  }
}
```

I get this error

```
Error: Not Authorised!
    at normalizeOptions (/Users/playra/prisma-examples/node/graphql-auth/node_modules/graphql-shield/dist/shield.js:25:44)
    at shield (/Users/playra/prisma-examples/node/graphql-auth/node_modules/graphql-shield/dist/shield.js:38:31)
    at Object.<anonymous> (/Users/playra/prisma-examples/node/graphql-auth/src/permissions/index.js:21:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/playra/prisma-examples/node/graphql-auth/src/index.js:4:25)
```

Updated HTTP HEADERS
```
{
  "Authorization": "Bearer ….”
}
```

But request

```
{
  me {
    id
    name
    email
  }
}
```

with the same HTTP HEADERS works.
What is the problem?

<img width="1440" alt="Screenshot 2019-09-20 at 17 33 53" src="https://user-images.githubusercontent.com/6774813/65335287-d3848700-dbcc-11e9-9b9d-fce77ea86e2b.png">

**Comment by gHashTag** [comment]
For two years, observe your project, it is shocking that you do not have testers who will verify what you write in the documentation.
Anyone answer?

**Comment by muzaffersenkal** [comment]
Hi gHashTag,

Did you solve problem ? Can you share permission file ?

**Comment by gHashTag** [comment]
Нет

**Comment by nikolasburk** [comment]
Hey @gHashTag, thanks a lot for opening this issue and apologies for the delay! Unfortunately we don't have the capacity at the moment to maintain the examples for Prisma 1 (since we're focusing all our resources on the development of the new Prisma Framework, more info [here](https://github.com/prisma/prisma/issues/4898)).

I'll leave the issue open as long as the error persists, feel free to close it when you've found a fix.  We definitely also welcome PRs to fix it 🙂 🙏

**Comment by gHashTag** [comment]
@nikolasburk Thank you I switched to AWS Amplify, which is very pleased.
